[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
# runner = "./qemu.sh"
runner = "gdb-multiarch -command=debug/debug.gdb"
rustflags = [
    "-C", "target-cpu=cortex-a53",
    "-C", "link-arg=--script=.cargo/layout.ld",
    "-C", "link-arg=--no-dynamic-linker",

    # # link to libsd.a
    # "-C", "link-arg=-L.cargo",
    # "-C", "link-arg=-lsd",
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
